 /*
 * felica_nfc_library_error.h
 * Copyright 2008 Sony Corporation
 *
 * [CAUTION] This file is automatically generated. Do not edit this file.
 */
#ifndef __FELICA_NFC_LIBRARY_ERROR_H__
#define __FELICA_NFC_LIBRARY_ERROR_H__

#define	FELICA_NFC_E_INVALID_ARGUMENT					0x80C00001	/* 引数が異常です。 */
#define	FELICA_NFC_E_NOT_IMPLEMENT						0x80C00002	/* 実装されていません。 */
#define	FELICA_NFC_E_INVALID_MODE						0x80C00003	/* FeliCaライブラリが動作中です。 */
#define	FELICA_NFC_E_MEMORY_ALLOCATE					0x80C00004	/* メモリが確保できません。 */
#define	FELICA_NFC_E_NOT_INITIALIZE						0x80C00005	/* ライブラリが初期化されていません。 */
#define	FELICA_NFC_E_INVALID_PORT_LIST					0x80C00006	/* ポートリスト名が不正です。 */
#define	FELICA_NFC_E_INVALID_PORT_NAME					0x80C00007	/* ポート名が不正です。 */
#define	FELICA_NFC_E_INVALID_PLUGINS_DIR				0x80C00008	/* プラグインディレクトリが不正です。 */
#define	FELICA_NFC_E_INVALID_PLUGIN_NAME				0x80C00009	/* プラグインファイル名が不正です。 */
#define	FELICA_NFC_E_INVALID_PLUGIN						0x80C0000a	/* プラグインファイルが不正です。 */
#define	FELICA_NFC_E_NO_PLUGIN							0x80C0000b	/* プラグインファイルが存在しません。 */
#define	FELICA_NFC_E_CREATE_THREAD						0x80C0000c	/* スレッドが生成できません。 */
#define	FELICA_NFC_E_NOT_PORT_OPENED					0x80C0000d	/* ポートがオープンされていません。 */
#define	FELICA_NFC_E_NO_CALLBACK_PARAM					0x80C0000e	/* コールバックパラメータが設定されていません。 */
#define	FELICA_NFC_E_NOT_CREATE_MESSAGE					0x80C0000f	/* コールバック用メッセージが生成できません。 */
#define	FELICA_NFC_E_TIME_OUT							0x80C00010	/* NFCライブラリでタイムアウトが発生しました。 */
#define	FELICA_NFC_E_CALLBACK							0x80C00011	/* コールバック呼び出しに失敗しました。 */
#define	FELICA_NFC_E_ALREADY_INITIALIZED				0x80C00012	/* ライブラリはすでに初期化されています。 */
#define	FELICA_NFC_E_PORT_OPENED						0x80C00013	/* すでにポートがオープンされています。 */
#define	FELICA_NFC_E_DRIVER_STATUS						0x80C00014	/* ドライバステータスが不正です。 */
#define	FELICA_NFC_E_INVALID_TARGET_DEVICE_TYPE			0x80C00015	/* 捕捉したターゲットデバイスタイプが不正です。 */
#define	FELICA_NFC_E_FORBIDDEN_OPERARION				0x80C00016  /* 禁止されている操作です。 */

#define	FELICA_NFC_E_TARGET_DEVICE_NOT_FOUND			0x80C00050	/* 捕捉デバイスが見つかりませんでした。 */
#define	FELICA_NFC_E_TARGET_DEVICE_TIMEOUT				0x80C00051	/* 捕捉デバイス使用開始要求が時間内にありませんでした。 */
#define	FELICA_NFC_E_TARGET_DEVICE_ACCESS				0x80C00052	/* ターゲットデバイスアクセスでのエラーがドライバより通知されました。 */
#define	FELICA_NFC_E_TARGET_DEVICE						0x80C00053	/* ターゲットデバイスアクセスでの不明エラーがドライバより通知されました。 */

#define	FELICA_NFC_E_DEVICE_MODE						0x80C00071	/* モード以降エラーがドライバ内で発生しています。 */
#define	FELICA_NFC_E_DEVICE_INITIALIZE					0x80C00072	/* FeliCaポートデバイスの初期化処理エラーです。 */
#define	FELICA_NFC_E_DEVICE_TEMPERATURE_ERROR			0x80C00073	/* FeliCaポートデバイスが温度異常状態です。 */
#define	FELICA_NFC_E_DEVICE_TEMPERATURE_FATAL_ERROR		0x80C00074	/* FeliCaポートデバイスが温度異常状態により、使用できない状態です。 */
#define	FELICA_NFC_E_DEVICE_READER_WRITER_DISCONNECTED	0x80C00075	/* FeliCaポートデバイスが切断されました。 */
#define	FELICA_NFC_E_DEVICE_ERROR						0x80C00076	/* FeliCaポートデバイスで不明なエラーが発生しています。 */

#define	FELICA_NFC_E_REGISTRY							0x80C00101	/* レジストリアクセスに失敗しました。 */
#define	FELICA_NFC_E_INVALID_DIR						0x80C00102	/* フォルダが存在しないか不正です。 */
#define	FELICA_NFC_E_INVALID_FILE						0x80C00103	/* ファイルが存在しないか不正です。 */
#define	FELICA_NFC_E_FILE_ACCESS						0x80C00104	/* ファイルアクセスに失敗しました。 */

#define	FELICA_NFCP_E_INVALID_ARGUMENT					0x80A00001	/* プラグインへの引数が異常です。 */
#define	FELICA_NFCP_E_INITIALIZE_DRIVER					0x80A00002	/* ドライバの初期化に失敗しました。 */
#define	FELICA_NFCP_E_MEMORY_ALLOCATE					0x80A00003	/* メモリが確保できません。 */
#define	FELICA_NFCP_E_INVALID_PORT_NAME					0x80A00004	/* ポート名が不正です。 */
#define	FELICA_NFCP_E_NOT_PORT_OPENED					0x80A00005	/* ポートがオープンされていません。 */
#define	FELICA_NFCP_E_OPENED							0x80A00006	/* すでにポートがオープンされています。 */
#define	FELICA_NFCP_E_INVALID_RESPONSE					0x80A00007	/* ドライバからのレスポンスが不正です。 */

#define	FELICA_NFC_E_DRIVER_ERROR						0x80080000	/* ドライバでエラーが発生しました。 */

#endif // __FELICA_NFC_LIBRARY_ERROR_H__
